---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, netapp console' 
summary: Saiba o que há de novo no suporte ao Azure NetApp Files no NetApp Console. 
---
= O que há de novo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba o que há de novo no Azure NetApp Files no NetApp Console.



== 06 de outubro de 2025



=== BlueXP agora é NetApp Console

O BlueXP foi renomeado e redesenhado para refletir melhor seu papel no gerenciamento de sua infraestrutura de dados.

O NetApp Console fornece gerenciamento centralizado de serviços de armazenamento e dados em ambientes locais e na nuvem em nível empresarial, fornecendo insights em tempo real, fluxos de trabalho mais rápidos e administração simplificada.

Para obter detalhes sobre o que mudou, consulte o https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de versão do NetApp Console"] .



== 13 de janeiro de 2025



=== Recursos de rede agora suportados no BlueXP

Ao configurar um volume no Azure NetApp Files do BlueXP, agora você pode indicar recursos de rede.  Isso está alinhado com a funcionalidade disponível no Azure NetApp Files nativo.



== 12 de junho de 2024



=== Nova permissão necessária

A seguinte permissão agora é necessária para gerenciar volumes do Azure NetApp Files do BlueXP:

Microsoft.Network/virtualNetworks/sub-redes/leitura

Essa permissão é necessária para ler uma sub-rede de rede virtual.

Se você estiver gerenciando o Azure NetApp Files do BlueXP, precisará adicionar essa permissão à função personalizada associada ao aplicativo Microsoft Entra que você criou anteriormente.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Aprenda a configurar um aplicativo Microsoft Entra e visualizar as permissões de função personalizadas"] .



== 22 de abril de 2024



=== Modelos de volume não são mais suportados

Não é mais possível criar um volume a partir de um modelo. Esta ação foi associada ao serviço de correção BlueXP , que não está mais disponível.



== 11 de abril de 2021



=== Suporte para modelos de volume

Um novo serviço de Modelos de Aplicativo permite que você configure um modelo de volume para o Azure NetApp Files.  O modelo deve facilitar seu trabalho porque certos parâmetros de volume já estarão definidos no modelo, como pool de capacidade, tamanho, protocolo, VNet e sub-rede onde o volume deve residir e muito mais.  Quando um parâmetro já estiver predefinido, você pode simplesmente pular para o próximo parâmetro de volume.



== 8 de março de 2021



=== Alterar dinamicamente os níveis de serviço

Agora você pode alterar dinamicamente o nível de serviço de um volume para atender às necessidades de carga de trabalho e otimizar seus custos.  O volume é movido para o outro pool de capacidade sem impacto no volume.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-manage-volumes.html#change-the-volumes-service-level["Aprenda como alterar o nível de serviço de um volume"] .



== 3 de agosto de 2020



=== Configuração e gerenciamento do Azure NetApp Files

Configure e gerencie o Azure NetApp Files diretamente do Cloud Manager.  Depois de criar um sistema do Azure NetApp Files , você pode concluir as seguintes tarefas:

* Crie volumes NFS e SMB.
* Gerenciar pools de capacidade e instantâneos de volume
+
O Cloud Manager permite que você crie, exclua e restaure instantâneos de volume.  Você também pode criar novos pools de capacidade e especificar seus níveis de serviço.

* Edite um volume alterando seu tamanho e gerenciando tags.


A capacidade de criar e gerenciar o Azure NetApp Files diretamente do Cloud Manager substitui a funcionalidade anterior de migração de dados.



== 5 de abril de 2020



=== Migração de dados para o Azure NetApp Files

Agora você pode migrar dados NFS ou SMB para o Azure NetApp Files diretamente do Cloud Manager.  As sincronizações de dados são fornecidas pelo BlueXP copy and sync.
